In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels=data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features=data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X=features
y=labels

In [9]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
y

array([0., 0., 0., ..., 1., 1., 1.])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler=MinMaxScaler()

In [17]:
X_train=scaler.fit_transform(X_train)

In [18]:
X_test=scaler.transform(X_test)

In [19]:
from keras.layers import Dense
from keras.models import Sequential

In [21]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.fit(X_train,y_train,epochs=50,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
919/919 [==============================] - 0s 341us/step - loss: 0.7227 - accuracy: 0.3471
Epoch 2/50
919/919 [==============================] - 0s 54us/step - loss: 0.6989 - accuracy: 0.4842
Epoch 3/50
919/919 [==============================] - 0s 55us/step - loss: 0.6913 - accuracy: 0.5495
Epoch 4/50
919/919 [==============================] - 0s 53us/step - loss: 0.6875 - accuracy: 0.5495
Epoch 5/50
919/919 [==============================] - 0s 55us/step - loss: 0.6844 - accuracy: 0.5495
Epoch 6/50
919/919 [==============================] - 0s 56us/step - loss: 0.6813 - accuracy: 0.5495
Epoch 7/50
919/919 [==============================] - 0s 53us/step - loss: 0.6778 - accuracy: 0.5495
Epoch 8/50
919/919 [==============================] - 0s 54us/step - loss: 0.6734 - accuracy: 0.5495
Epoch 9/50
919/919 [==============================] - 0s 53us/step - loss: 0.6665 - accuracy: 0.5495
Epoch 10/50
919/919 [=====================

In [23]:
predictions=model.predict_classes(X_test)

In [24]:
from sklearn.metrics import confusion_matrix,classification_report

In [25]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[255   2]
 [ 28 168]]
              precision    recall  f1-score   support

         0.0       0.90      0.99      0.94       257
         1.0       0.99      0.86      0.92       196

    accuracy                           0.93       453
   macro avg       0.94      0.92      0.93       453
weighted avg       0.94      0.93      0.93       453



In [26]:
model.save('myfirstmodel.h5')